ignore:
  - vulnerability: CVE-2025-60876
    package:
      name: busybox
      
  - vulnerability: CVE-2025-60876
    package:
      name: busybox-binsh
      
  - vulnerability: CVE-2025-60876
    package:
      name: ssl_client